//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        public Account()
        {
            this.SubjectsAccounts = new HashSet<SubjectsAccount>();
            this.Syllabuses = new HashSet<Syllabus>();
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Username")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Password")]
        [PasswordPropertyText]
        public string Password { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên đầy đủ")]
        [DisplayName("Tên đầy đủ")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập trình độ")]
        [DisplayName("Trình độ")]
        public string Degree { get; set; }
        [Required]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Số điện thoại chưa đúng định dạng")]
        [DisplayName("Số điện thoại")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [EmailAddress(ErrorMessage = "Email chưa đúng định dạng")]
        [DisplayName("Địa chỉ Email")]
        public string Email { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<SubjectsAccount> SubjectsAccounts { get; set; }
        public virtual ICollection<Syllabus> Syllabuses { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
