//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Faculties = new HashSet<Faculty>();
            this.Syllabuses = new HashSet<Syllabus>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên lớp")]
        [DisplayName("Tên lớp")]
        public string Name { get; set; }

        [DisplayName("Có phải văn phòng khoa?")]
        public bool IsOfficeFacility { get; set; }

        [DisplayName("Thuộc cơ sở")]
        public int FacilityID { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Syllabus> Syllabuses { get; set; }
    }
}
