//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Classrooms = new HashSet<Classroom>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên cơ sở")]
        [DisplayName("Tên cở sở")]
        public string Name { get; set; }
        [DisplayName("Địa chỉ cở sở")]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string Address { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual ICollection<Classroom> Classrooms { get; set; }
    }
}
