//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Accounts = new HashSet<Account>();
            this.Programs = new HashSet<Program>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên khoa (Tiếng việt)")]
        [DisplayName("Tên khoa (Tiếng việt)")]
        public string VietNameseName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên khoa (Tiếng anh)")]
        [DisplayName("Tên khoa (Tiếng anh)")]
        public string EnglishName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [DisplayName("Số điện thoại khoa")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Số điện thoại chưa đúng định dạng")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn văn phòng khoa")]
        [DisplayName("Văn phòng khoa")]
        public int ClassroomID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thời gian đào tạo")]
        [DisplayName("Thời gian đào tạo")]
        [Range(1, 5, ErrorMessage = "Thời gian đào tạo trong khoảng [1, 5] năm")]
        public int TrainingTime { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Classroom Classroom { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
