//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectType
    {
        public SubjectType()
        {
            this.Subjects = new HashSet<Subject>();
            this.SubjectTypes1 = new HashSet<SubjectType>();
            this.SubjectTypes11 = new HashSet<SubjectType>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SubSubjectTypeID { get; set; }
        public Nullable<int> SubTwoSubjectTypeID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<SubjectType> SubjectTypes1 { get; set; }
        public virtual SubjectType SubjectType1 { get; set; }
        public virtual ICollection<SubjectType> SubjectTypes11 { get; set; }
        public virtual SubjectType SubjectType2 { get; set; }
    }
}
