//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectsAccount
    {
        public int SubjectID { get; set; }
        public int AccountID { get; set; }
        public bool IsSyllabusEditor { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
