//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Subject
    {
        public Subject()
        {
            this.SubjectsAccounts = new HashSet<SubjectsAccount>();
            this.Syllabuses = new HashSet<Syllabus>();
            this.Subjects1 = new HashSet<Subject>();
            this.Subjects = new HashSet<Subject>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên môn học")]
        [DisplayName("Tên môn học")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mã môn học")]
        [DisplayName("Mã môn học(Mã học phần)")]
        public string PartialCode { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số tín chỉ")]
        [DisplayName("Sô tín chỉ")]
        public int CreditNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số tiết lý thuyết")]
        [DisplayName("Số tiết lý thuyết")]
        public int TheoryNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số tiết thực hành")]
        [DisplayName("Thời gian thực hành")]
        public int PracticeNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập trình độ học vấn")]
        [DisplayName("Trình độ học vấn")]
        public string LearningLevel { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập học kỳ")]
        [Range(1, 8, ErrorMessage = "Thời gian học kỳ trong khoảng [1, 8] học kỳ")]
        [DisplayName("Học tại học kỳ")]
        public int SemesterNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mô tả môn học")]
        [AllowHtml]
        [DisplayName("Mô tả môn học")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mục đích môn học")]
        [AllowHtml]
        [DisplayName("Mục đích môn học")]
        public string Purpose { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn khoa")]
        [DisplayName("Thuộc khoa")]
        public Nullable<int> FacultyID { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn loại môn học")]
        [DisplayName("Loại môn học")]
        public int SubjectTypeID { get; set; }

        [DisplayName("Môn học có bắt buộc hay không?")]
        public bool Form { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual SubjectType SubjectType { get; set; }
        public virtual ICollection<SubjectsAccount> SubjectsAccounts { get; set; }
        public virtual ICollection<Syllabus> Syllabuses { get; set; }
        public virtual ICollection<Subject> Subjects1 { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
