//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramBuilder.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Syllabus
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên học phần")]
        [DisplayName("Tên học phần")]
        public string VietnameseName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên học phần (Tiếng anh)")]
        [DisplayName("Tên học phần (Tiếng anh)")]
        public string EnglishName { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng chọn khối kiến thức")]
        [DisplayName("Môn học thuộc khối kiến thức")]
        public string KnowldgeType { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập thời gian học")]
        [DisplayName("Thời gian học")]
        public string LearningTimeDetail { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập yêu cầu môn học")]
        [DisplayName("Yêu cầu môn học")]
        public string Requirement { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập kế hoạch giảng dạy học tập cụ thể")]
        [DisplayName("Kế hoạch giảng dạy học tập cụ thể")]
        public string Planning { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập tài liệu phục vụ môn học")]
        [DisplayName("Tài liệu phục vụ môn học")]
        public string DocumentReference { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập phương pháp đánh giá kết quả học tập của sinh viên")]
        [DisplayName("Phương pháp đánh giá kết quả học tập của sinh viên")]        
        public string LearningOutcomeEvaluate { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập cách liên lạc giảng viên")]
        [DisplayName("Cách liên lạc giảng viên")]
        public string LecturerContact { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập mô tả vắn tắt nội dung học phần")]
        [DisplayName("Mô tả vắn tắt nội dung học phần")]
        public string ShortDescription { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập kết quả dự kiến môn học/chuẩn đầu ra")]
        [DisplayName("Kết quả dự kiến môn học/chuẩn đầu ra")]
        public string OutcomeContent { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập ma trận tích hợp giữa Chuẩn đầu ra môn học và Chuẩn đầu ra của Chương trình đào tạo")]
        [DisplayName("Ma trận tích hợp giữa Chuẩn đầu ra môn học và Chuẩn đầu ra của Chương trình đào tạo")]
        public string OutcomeMaxtrixMapping { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Vui lòng nhập ma trận tích hợp giữa chuẩn đầu ra môn học, hoạt động giảng dạy ....")]
        [DisplayName(" Ma trận tích hợp giữa chuẩn đầu ra môn học, hoạt động giảng dạy, phương pháp đánh giá với chuẩn đầu ra chương trình đào tạo")]
        public string OutcomeMappingDescription { get; set; }

        public int CreatedAccountID { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn địa điểm học")]
        [DisplayName("Địa điểm học")]
        public int ClassroomID { get; set; }

        [DisplayName("Chọn môn học")]
        public int SubjectID { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Classroom Classroom { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
